import type { PacketField } from '../../types';
import { calculatePacketLayout, getFieldBitWidth } from '../bitPacking';

export function generateRobloxCode(fields: PacketField[]): string {
  const { layoutFields, totalBytes } = calculatePacketLayout(fields);
  const hasHalfFloat = fields.some(f => f.type === 'float' && f.floatType === 'half');
  
  let code = `-- Roblox Luau Buffer Serialization Generator
-- Automatically generated by BitPacker: Visual Game Netcode Designer

local NetPacket = {}
NetPacket.__index = NetPacket
`;

  // Inject Half Float helpers if required
  if (hasHalfFloat) {
    code += `
-- Packs a float into a 16-bit half-float value (IEEE 754 binary16)
local function packHalf(val: number): number
    if val == 0 then return 0 end
    local sign = val < 0 and 0x8000 or 0
    val = math.abs(val)
    if val >= 65504 then return bit32.bor(sign, 0x7c00) end
    if val < 0.00006103515625 then return sign end -- Underflow
    
    local exponent = math.floor(math.log(val, 2))
    local mantissa = math.round((val / (2^exponent) - 1) * 1024)
    exponent = math.clamp(exponent + 15, 0, 31)
    return bit32.bor(sign, bit32.lshift(exponent, 10), bit32.band(mantissa, 0x3ff))
end

-- Unpacks a 16-bit half-float back to a standard float
local function unpackHalf(val: number): number
    local sign = bit32.band(val, 0x8000) ~= 0 and -1 or 1
    local exponent = bit32.band(bit32.rshift(val, 10), 0x1f)
    local mantissa = bit32.band(val, 0x3ff)
    if exponent == 0 then
        return sign * (mantissa / 1024) * 0.00006103515625
    elseif exponent == 31 then
        return mantissa == 0 and sign * math.huge or 0/0
    end
    return sign * (1 + mantissa / 1024) * (2^(exponent - 15))
end
`;
  }

  code += `
function NetPacket.new()
    local self = setmetatable({}, NetPacket)
    -- Initialize fields with default values
`;

  // Initialize fields
  fields.forEach(f => {
    if (f.type === 'bool') {
      code += `    self.${f.name} = false\n`;
    } else if (f.type === 'int' || f.type === 'float') {
      code += `    self.${f.name} = 0\n`;
    } else if (f.type === 'vector3') {
      code += `    self.${f.name} = Vector3.zero\n`;
    } else if (f.type === 'string') {
      code += `    self.${f.name} = ""\n`;
    }
  });

  code += `    return self
end

-- Serializes this packet object into a Luau buffer (Size: ${totalBytes} bytes)
function NetPacket:Serialize(): buffer
    local buf = buffer.create(${totalBytes})
`;

  // We will group bit-fields by byte block to generate clean write registers
  const byteRegisters: Record<number, { field: typeof layoutFields[0]; startBit: number; endBit: number }[]> = {};
  
  layoutFields.forEach(lf => {
    if (lf.bitWidthCalculated <= 8 && lf.byteIndexStart === lf.byteIndexEnd) {
      const byteIdx = lf.byteIndexStart;
      if (!byteRegisters[byteIdx]) byteRegisters[byteIdx] = [];
      byteRegisters[byteIdx].push({
        field: lf,
        startBit: lf.bitOffsetInByteStart,
        endBit: lf.bitOffsetInByteEnd
      });
    }
  });

  let currentByte = 0;
  while (currentByte < totalBytes) {
    const prevByte = currentByte;
    const bitFields = byteRegisters[currentByte];
    
    if (bitFields && bitFields.length > 0) {
      code += `\n    -- Pack byte ${currentByte}\n`;
      code += `    local reg_${currentByte} = 0\n`;
      
      bitFields.forEach(bf => {
        const mask = (1 << bf.field.bitWidthCalculated) - 1;
        if (bf.field.type === 'bool') {
          code += `    if self.${bf.field.name} then\n`;
          code += `        reg_${currentByte} = bit32.bor(reg_${currentByte}, ${1 << bf.startBit})\n`;
          code += `    end\n`;
        } else if (bf.field.type === 'int') {
          let valExpr = `self.${bf.field.name}`;
          if (bf.field.minValue !== undefined) {
            valExpr = `(self.${bf.field.name} - ${bf.field.minValue})`;
          }
          code += `    local val_${bf.field.name} = math.clamp(math.round(${valExpr}), 0, ${mask})\n`;
          code += `    reg_${currentByte} = bit32.bor(reg_${currentByte}, bit32.lshift(val_${bf.field.name}, ${bf.startBit}))\n`;
        } else if (bf.field.type === 'float' && bf.field.floatType === 'quantized') {
          const min = bf.field.minValue ?? 0;
          const max = bf.field.maxValue ?? 1;
          const prec = bf.field.precision ?? 0.1;
          code += `    local val_${bf.field.name} = math.clamp(self.${bf.field.name}, ${min}, ${max})\n`;
          code += `    local step_${bf.field.name} = math.round((val_${bf.field.name} - ${min}) / ${prec})\n`;
          code += `    reg_${currentByte} = bit32.bor(reg_${currentByte}, bit32.lshift(step_${bf.field.name}, ${bf.startBit}))\n`;
        }
      });
      
      code += `    buffer.writeu8(buf, ${currentByte}, reg_${currentByte})\n`;
      currentByte++;
    } else {
      const fieldStartingHere = layoutFields.find(lf => lf.byteIndexStart === currentByte);
      
      if (fieldStartingHere) {
        code += `\n    -- Field: ${fieldStartingHere.name} (${fieldStartingHere.type})\n`;
        
        if (fieldStartingHere.type === 'int' && fieldStartingHere.bitWidthCalculated > 8) {
          const width = fieldStartingHere.bitWidthCalculated;
          const writeType = width <= 16 ? 'u16' : 'u32';
          let valExpr = `self.${fieldStartingHere.name}`;
          if (fieldStartingHere.minValue !== undefined) {
            valExpr = `(self.${fieldStartingHere.name} - ${fieldStartingHere.minValue})`;
          }
          code += `    buffer.write${writeType}(buf, ${currentByte}, math.round(${valExpr}))\n`;
          currentByte += width / 8;
        } else if (fieldStartingHere.type === 'float') {
          if (fieldStartingHere.floatType === 'single') {
            code += `    buffer.writef32(buf, ${currentByte}, self.${fieldStartingHere.name})\n`;
            currentByte += 4;
          } else if (fieldStartingHere.floatType === 'half') {
            code += `    buffer.writeu16(buf, ${currentByte}, packHalf(self.${fieldStartingHere.name}))\n`;
            currentByte += 2;
          }
        } else if (fieldStartingHere.type === 'vector3') {
          if (fieldStartingHere.vectorType === 'full') {
            code += `    buffer.writef32(buf, ${currentByte}, self.${fieldStartingHere.name}.X)\n`;
            code += `    buffer.writef32(buf, ${currentByte + 4}, self.${fieldStartingHere.name}.Y)\n`;
            code += `    buffer.writef32(buf, ${currentByte + 8}, self.${fieldStartingHere.name}.Z)\n`;
            currentByte += 12;
          } else {
            const min = fieldStartingHere.minValue ?? -50;
            const max = fieldStartingHere.maxValue ?? 50;
            const prec = fieldStartingHere.vectorPrecision ?? 0.1;
            const compWidth = getFieldBitWidth(fieldStartingHere) / 3;
            const writeType = compWidth <= 8 ? 'u8' : (compWidth <= 16 ? 'u16' : 'u32');
            const inc = compWidth <= 8 ? 1 : (compWidth <= 16 ? 2 : 4);
            
            code += `    local function packComp(val)\n`;
            code += `        local clamped = math.clamp(val, ${min}, ${max})\n`;
            code += `        return math.round((clamped - ${min}) / ${prec})\n`;
            code += `    end\n`;
            code += `    buffer.write${writeType}(buf, ${currentByte}, packComp(self.${fieldStartingHere.name}.X))\n`;
            code += `    buffer.write${writeType}(buf, ${currentByte + inc}, packComp(self.${fieldStartingHere.name}.Y))\n`;
            code += `    buffer.write${writeType}(buf, ${currentByte + inc * 2}, packComp(self.${fieldStartingHere.name}.Z))\n`;
            currentByte += inc * 3;
          }
        } else if (fieldStartingHere.type === 'string') {
          const maxLen = fieldStartingHere.maxStringLength || 16;
          if (fieldStartingHere.stringType === 'dynamic') {
            code += `    local strLen = math.min(#self.${fieldStartingHere.name}, ${maxLen})\n`;
            if (maxLen < 256) {
              code += `    buffer.writeu8(buf, ${currentByte}, strLen)\n`;
              code += `    buffer.writestring(buf, ${currentByte + 1}, self.${fieldStartingHere.name}, strLen)\n`;
              currentByte += 1 + maxLen;
            } else {
              code += `    buffer.writeu16(buf, ${currentByte}, strLen)\n`;
              code += `    buffer.writestring(buf, ${currentByte + 2}, self.${fieldStartingHere.name}, strLen)\n`;
              currentByte += 2 + maxLen;
            }
          } else {
            code += `    local str_${fieldStartingHere.name} = string.sub(self.${fieldStartingHere.name}, 1, ${maxLen})\n`;
            code += `    str_${fieldStartingHere.name} = str_${fieldStartingHere.name} .. string.rep(" ", ${maxLen} - #str_${fieldStartingHere.name})\n`;
            code += `    buffer.writestring(buf, ${currentByte}, str_${fieldStartingHere.name}, ${maxLen})\n`;
            currentByte += maxLen;
          }
        }
      }
    }

    // Safety fallback to prevent infinite loops
    if (currentByte <= prevByte) {
      currentByte++;
    }
  }

  code += `    return buf
end

-- Deserializes a packet object from a Luau buffer
function NetPacket.Deserialize(buf: buffer): any
    local self = NetPacket.new()
`;

  currentByte = 0;
  while (currentByte < totalBytes) {
    const prevByte = currentByte;
    const bitFields = byteRegisters[currentByte];
    
    if (bitFields && bitFields.length > 0) {
      code += `\n    -- Unpack byte ${currentByte}\n`;
      code += `    local reg_${currentByte} = buffer.readu8(buf, ${currentByte})\n`;
      
      bitFields.forEach(bf => {
        const mask = (1 << bf.field.bitWidthCalculated) - 1;
        
        if (bf.field.type === 'bool') {
          code += `    self.${bf.field.name} = bit32.band(bit32.rshift(reg_${currentByte}, ${bf.startBit}), 1) == 1\n`;
        } else if (bf.field.type === 'int') {
          let expr = `bit32.band(bit32.rshift(reg_${currentByte}, ${bf.startBit}), ${mask})`;
          if (bf.field.minValue !== undefined) {
            expr = `${expr} + ${bf.field.minValue}`;
          }
          code += `    self.${bf.field.name} = ${expr}\n`;
        } else if (bf.field.type === 'float' && bf.field.floatType === 'quantized') {
          const min = bf.field.minValue ?? 0;
          const prec = bf.field.precision ?? 0.1;
          code += `    local step_${bf.field.name} = bit32.band(bit32.rshift(reg_${currentByte}, ${bf.startBit}), ${mask})\n`;
          code += `    self.${bf.field.name} = step_${bf.field.name} * ${prec} + ${min}\n`;
        }
      });
      
      currentByte++;
    } else {
      const fieldStartingHere = layoutFields.find(lf => lf.byteIndexStart === currentByte);
      
      if (fieldStartingHere) {
        code += `\n    -- Field: ${fieldStartingHere.name} (${fieldStartingHere.type})\n`;
        
        if (fieldStartingHere.type === 'int' && fieldStartingHere.bitWidthCalculated > 8) {
          const width = fieldStartingHere.bitWidthCalculated;
          const readType = width <= 16 ? 'u16' : 'u32';
          let expr = `buffer.read${readType}(buf, ${currentByte})`;
          if (fieldStartingHere.minValue !== undefined) {
            expr = `${expr} + ${fieldStartingHere.minValue}`;
          }
          code += `    self.${fieldStartingHere.name} = ${expr}\n`;
          currentByte += width / 8;
        } else if (fieldStartingHere.type === 'float') {
          if (fieldStartingHere.floatType === 'single') {
            code += `    self.${fieldStartingHere.name} = buffer.readf32(buf, ${currentByte})\n`;
            currentByte += 4;
          } else if (fieldStartingHere.floatType === 'half') {
            code += `    self.${fieldStartingHere.name} = unpackHalf(buffer.readu16(buf, ${currentByte}))\n`;
            currentByte += 2;
          }
        } else if (fieldStartingHere.type === 'vector3') {
          if (fieldStartingHere.vectorType === 'full') {
            code += `    local x = buffer.readf32(buf, ${currentByte})\n`;
            code += `    local y = buffer.readf32(buf, ${currentByte + 4})\n`;
            code += `    local z = buffer.readf32(buf, ${currentByte + 8})\n`;
            code += `    self.${fieldStartingHere.name} = Vector3.new(x, y, z)\n`;
            currentByte += 12;
          } else {
            const min = fieldStartingHere.minValue ?? -50;
            const prec = fieldStartingHere.vectorPrecision ?? 0.1;
            const compWidth = getFieldBitWidth(fieldStartingHere) / 3;
            const readType = compWidth <= 8 ? 'u8' : (compWidth <= 16 ? 'u16' : 'u32');
            const inc = compWidth <= 8 ? 1 : (compWidth <= 16 ? 2 : 4);
            
            code += `    local function unpackComp(step)\n`;
            code += `        return step * ${prec} + ${min}\n`;
            code += `    end\n`;
            code += `    local vx = unpackComp(buffer.read${readType}(buf, ${currentByte}))\n`;
            code += `    local vy = unpackComp(buffer.read${readType}(buf, ${currentByte + inc}))\n`;
            code += `    local vz = unpackComp(buffer.read${readType}(buf, ${currentByte + inc * 2}))\n`;
            code += `    self.${fieldStartingHere.name} = Vector3.new(vx, vy, vz)\n`;
            currentByte += inc * 3;
          }
        } else if (fieldStartingHere.type === 'string') {
          const maxLen = fieldStartingHere.maxStringLength || 16;
          if (fieldStartingHere.stringType === 'dynamic') {
            if (maxLen < 256) {
              code += `    local strLen = buffer.readu8(buf, ${currentByte})\n`;
              code += `    self.${fieldStartingHere.name} = buffer.readstring(buf, ${currentByte + 1}, strLen)\n`;
              currentByte += 1 + maxLen;
            } else {
              code += `    local strLen = buffer.readu16(buf, ${currentByte})\n`;
              code += `    self.${fieldStartingHere.name} = buffer.readstring(buf, ${currentByte + 2}, strLen)\n`;
              currentByte += 2 + maxLen;
            }
          } else {
            code += `    local rawStr = buffer.readstring(buf, ${currentByte}, ${maxLen})\n`;
            code += `    self.${fieldStartingHere.name} = string.gsub(rawStr, "%s+$", "")\n`;
            currentByte += maxLen;
          }
        }
      }
    }

    // Safety fallback
    if (currentByte <= prevByte) {
      currentByte++;
    }
  }

  code += `    return self
end

return NetPacket
`;

  return code;
}
