import type { PacketField } from '../../types';
import { calculatePacketLayout, getFieldBitWidth } from '../bitPacking';

export function generateSboxCode(fields: PacketField[]): string {
  const { layoutFields, totalBytes } = calculatePacketLayout(fields);
  
  let code = `// C# Binary Serialization for s&box
// Automatically generated by BitPacker: Visual Game Netcode Designer

using System.IO;
using System;

public struct NetworkPacket
{
`;

  // Fields declarations
  fields.forEach(f => {
    if (f.type === 'bool') {
      code += `    public bool ${f.name};\n`;
    } else if (f.type === 'int') {
      code += `    public int ${f.name};\n`;
    } else if (f.type === 'float') {
      code += `    public float ${f.name};\n`;
    } else if (f.type === 'vector3') {
      code += `    public Vector3 ${f.name}; // Needs a Vector3 type mapping\n`;
    } else if (f.type === 'string') {
      code += `    public string ${f.name};\n`;
    }
  });

  const hasVector = fields.some(f => f.type === 'vector3');
  
  code += `
    // Helper struct matching the layout size
    public const int PacketSize = ${totalBytes};

    // Serializes the struct fields into a BinaryWriter stream
    public void Write(BinaryWriter writer)
    {
`;

  // Pack bit-fields
  const byteRegisters: Record<number, { field: typeof layoutFields[0]; startBit: number; endBit: number }[]> = {};
  layoutFields.forEach(lf => {
    if (lf.bitWidthCalculated <= 8 && lf.byteIndexStart === lf.byteIndexEnd) {
      const byteIdx = lf.byteIndexStart;
      if (!byteRegisters[byteIdx]) byteRegisters[byteIdx] = [];
      byteRegisters[byteIdx].push({
        field: lf,
        startBit: lf.bitOffsetInByteStart,
        endBit: lf.bitOffsetInByteEnd
      });
    }
  });

  let currentByte = 0;
  while (currentByte < totalBytes) {
    const prevByte = currentByte;
    const bitFields = byteRegisters[currentByte];
    
    if (bitFields && bitFields.length > 0) {
      code += `        // Pack byte register ${currentByte}\n`;
      code += `        byte reg${currentByte} = 0;\n`;
      
      bitFields.forEach(bf => {
        const mask = (1 << bf.field.bitWidthCalculated) - 1;
        if (bf.field.type === 'bool') {
          code += `        if (${bf.field.name}) reg${currentByte} |= (byte)(1 << ${bf.startBit});\n`;
        } else if (bf.field.type === 'int') {
          let valExpr = bf.field.name;
          if (bf.field.minValue !== undefined) {
            valExpr = `(${bf.field.name} - ${bf.field.minValue})`;
          }
          code += `        int val_${bf.field.name} = Math.Clamp(${valExpr}, 0, ${mask});\n`;
          code += `        reg${currentByte} |= (byte)((val_${bf.field.name} & 0x${mask.toString(16)}) << ${bf.startBit});\n`;
        } else if (bf.field.type === 'float' && bf.field.floatType === 'quantized') {
          const min = bf.field.minValue ?? 0;
          const max = bf.field.maxValue ?? 1;
          const prec = bf.field.precision ?? 0.1;
          code += `        float clamped_${bf.field.name} = Math.Clamp(${bf.field.name}, ${min}f, ${max}f);\n`;
          code += `        int step_${bf.field.name} = (int)Math.Round((clamped_${bf.field.name} - ${min}f) / ${prec}f);\n`;
          code += `        reg${currentByte} |= (byte)((step_${bf.field.name} & 0x${mask.toString(16)}) << ${bf.startBit});\n`;
        }
      });
      
      code += `        writer.Write(reg${currentByte});\n`;
      currentByte++;
    } else {
      const fieldStartingHere = layoutFields.find(lf => lf.byteIndexStart === currentByte);
      if (fieldStartingHere) {
        code += `        // Field: ${fieldStartingHere.name} (${fieldStartingHere.type})\n`;
        
        if (fieldStartingHere.type === 'int' && fieldStartingHere.bitWidthCalculated > 8) {
          const width = fieldStartingHere.bitWidthCalculated;
          let valExpr = fieldStartingHere.name;
          if (fieldStartingHere.minValue !== undefined) {
            valExpr = `(${fieldStartingHere.name} - ${fieldStartingHere.minValue})`;
          }
          if (width <= 16) {
            code += `        writer.Write((ushort)${valExpr});\n`;
            currentByte += 2;
          } else {
            code += `        writer.Write((uint)${valExpr});\n`;
            currentByte += 4;
          }
        } else if (fieldStartingHere.type === 'float') {
          if (fieldStartingHere.floatType === 'single') {
            code += `        writer.Write(${fieldStartingHere.name});\n`;
            currentByte += 4;
          } else if (fieldStartingHere.floatType === 'half') {
            code += `        writer.Write((Half)${fieldStartingHere.name});\n`;
            currentByte += 2;
          }
        } else if (fieldStartingHere.type === 'vector3') {
          if (fieldStartingHere.vectorType === 'full') {
            code += `        writer.Write(${fieldStartingHere.name}.x);\n`;
            code += `        writer.Write(${fieldStartingHere.name}.y);\n`;
            code += `        writer.Write(${fieldStartingHere.name}.z);\n`;
            currentByte += 12;
          } else {
            const min = fieldStartingHere.minValue ?? -50;
            const max = fieldStartingHere.maxValue ?? 50;
            const prec = fieldStartingHere.vectorPrecision ?? 0.1;
            const compWidth = getFieldBitWidth(fieldStartingHere) / 3;
            const castType = compWidth <= 8 ? 'byte' : (compWidth <= 16 ? 'ushort' : 'uint');
            const inc = compWidth <= 8 ? 1 : (compWidth <= 16 ? 2 : 4);
            
            code += `        Func<float, ${castType}> packComp = (val) => {\n`;
            code += `            float clamped = Math.Clamp(val, ${min}f, ${max}f);\n`;
            code += `            return (${castType})Math.Round((clamped - ${min}f) / ${prec}f);\n`;
            code += `        };\n`;
            code += `        writer.Write(packComp(${fieldStartingHere.name}.x));\n`;
            code += `        writer.Write(packComp(${fieldStartingHere.name}.y));\n`;
            code += `        writer.Write(packComp(${fieldStartingHere.name}.z));\n`;
            currentByte += inc * 3;
          }
        } else if (fieldStartingHere.type === 'string') {
          const maxLen = fieldStartingHere.maxStringLength || 16;
          if (fieldStartingHere.stringType === 'dynamic') {
            code += `        string val_${fieldStartingHere.name} = ${fieldStartingHere.name} ?? "";\n`;
            code += `        byte[] stringBytes_${fieldStartingHere.name} = System.Text.Encoding.UTF8.GetBytes(val_${fieldStartingHere.name});\n`;
            code += `        int bytesToWrite_${fieldStartingHere.name} = Math.Min(stringBytes_${fieldStartingHere.name}.Length, ${maxLen});\n`;
            if (maxLen < 256) {
              code += `        writer.Write((byte)bytesToWrite_${fieldStartingHere.name});\n`;
              currentByte += 1;
            } else {
              code += `        writer.Write((ushort)bytesToWrite_${fieldStartingHere.name});\n`;
              currentByte += 2;
            }
            code += `        writer.Write(stringBytes_${fieldStartingHere.name}, 0, bytesToWrite_${fieldStartingHere.name});\n`;
            code += `        if (${maxLen} > bytesToWrite_${fieldStartingHere.name}) {\n`;
            code += `            writer.Write(new byte[${maxLen} - bytesToWrite_${fieldStartingHere.name}]);\n`;
            code += `        }\n`;
            currentByte += maxLen;
          } else {
            code += `        string val_${fieldStartingHere.name} = (${fieldStartingHere.name} ?? "").PadRight(${maxLen});\n`;
            code += `        byte[] stringBytes_${fieldStartingHere.name} = System.Text.Encoding.UTF8.GetBytes(val_${fieldStartingHere.name});\n`;
            code += `        writer.Write(stringBytes_${fieldStartingHere.name}, 0, ${maxLen});\n`;
            currentByte += maxLen;
          }
        }
      }
    }

    // Safety check to prevent infinite loop
    if (currentByte <= prevByte) {
      currentByte++;
    }
  }

  code += `    }

    // Deserializes the stream and returns a new NetworkPacket struct
    public static NetworkPacket Read(BinaryReader reader)
    {
        var packet = new NetworkPacket();
`;

  currentByte = 0;
  while (currentByte < totalBytes) {
    const prevByte = currentByte;
    const bitFields = byteRegisters[currentByte];
    
    if (bitFields && bitFields.length > 0) {
      code += `
        // Unpack byte register ${currentByte}\n`;
      code += `        byte reg${currentByte} = reader.ReadByte();\n`;
      
      bitFields.forEach(bf => {
        const mask = (1 << bf.field.bitWidthCalculated) - 1;
        if (bf.field.type === 'bool') {
          code += `        packet.${bf.field.name} = (reg${currentByte} & (1 << ${bf.startBit})) != 0;\n`;
        } else if (bf.field.type === 'int') {
          let expr = `(reg${currentByte} >> ${bf.startBit}) & 0x${mask.toString(16)}`;
          if (bf.field.minValue !== undefined) {
            expr = `(${expr}) + ${bf.field.minValue}`;
          }
          code += `        packet.${bf.field.name} = ${expr};\n`;
        } else if (bf.field.type === 'float' && bf.field.floatType === 'quantized') {
          const min = bf.field.minValue ?? 0;
          const prec = bf.field.precision ?? 0.1;
          code += `        int step_${bf.field.name} = (reg${currentByte} >> ${bf.startBit}) & 0x${mask.toString(16)};\n`;
          code += `        packet.${bf.field.name} = (float)(step_${bf.field.name} * ${prec}f + ${min}f);\n`;
        }
      });
      currentByte++;
    } else {
      const fieldStartingHere = layoutFields.find(lf => lf.byteIndexStart === currentByte);
      if (fieldStartingHere) {
        code += `        // Unpack field: ${fieldStartingHere.name} (${fieldStartingHere.type})\n`;
        
        if (fieldStartingHere.type === 'int' && fieldStartingHere.bitWidthCalculated > 8) {
          const width = fieldStartingHere.bitWidthCalculated;
          let readExpr = width <= 16 ? 'reader.ReadUInt16()' : 'reader.ReadUInt32()';
          if (fieldStartingHere.minValue !== undefined) {
            readExpr = `(${readExpr}) + ${fieldStartingHere.minValue}`;
          }
          code += `        packet.${fieldStartingHere.name} = (int)${readExpr};\n`;
          currentByte += width / 8;
        } else if (fieldStartingHere.type === 'float') {
          if (fieldStartingHere.floatType === 'single') {
            code += `        packet.${fieldStartingHere.name} = reader.ReadSingle();\n`;
            currentByte += 4;
          } else if (fieldStartingHere.floatType === 'half') {
            code += `        packet.${fieldStartingHere.name} = (float)reader.ReadHalf();\n`;
            currentByte += 2;
          }
        } else if (fieldStartingHere.type === 'vector3') {
          if (fieldStartingHere.vectorType === 'full') {
            code += `        packet.${fieldStartingHere.name}.x = reader.ReadSingle();\n`;
            code += `        packet.${fieldStartingHere.name}.y = reader.ReadSingle();\n`;
            code += `        packet.${fieldStartingHere.name}.z = reader.ReadSingle();\n`;
            currentByte += 12;
          } else {
            const min = fieldStartingHere.minValue ?? -50;
            const prec = fieldStartingHere.vectorPrecision ?? 0.1;
            const compWidth = getFieldBitWidth(fieldStartingHere) / 3;
            const readType = compWidth <= 8 ? 'Byte' : (compWidth <= 16 ? 'UInt16' : 'UInt32');
            const inc = compWidth <= 8 ? 1 : (compWidth <= 16 ? 2 : 4);
            
            code += `        Func<${readType}, float> unpackComp = (step) => {\n`;
            code += `            return (float)(step * ${prec}f + ${min}f);\n`;
            code += `        };\n`;
            code += `        packet.${fieldStartingHere.name}.x = unpackComp(reader.Read${readType}());\n`;
            code += `        packet.${fieldStartingHere.name}.y = unpackComp(reader.Read${readType}());\n`;
            code += `        packet.${fieldStartingHere.name}.z = unpackComp(reader.Read${readType}());\n`;
            currentByte += inc * 3;
          }
        } else if (fieldStartingHere.type === 'string') {
          const maxLen = fieldStartingHere.maxStringLength || 16;
          if (fieldStartingHere.stringType === 'dynamic') {
            if (maxLen < 256) {
              code += `        byte len_${fieldStartingHere.name} = reader.ReadByte();\n`;
              currentByte += 1;
            } else {
              code += `        ushort len_${fieldStartingHere.name} = reader.ReadUInt16();\n`;
              currentByte += 2;
            }
            code += `        byte[] raw_${fieldStartingHere.name} = reader.ReadBytes(${maxLen});\n`;
            code += `        packet.${fieldStartingHere.name} = System.Text.Encoding.UTF8.GetString(raw_${fieldStartingHere.name}, 0, len_${fieldStartingHere.name});\n`;
            currentByte += maxLen;
          } else {
            code += `        byte[] raw_${fieldStartingHere.name} = reader.ReadBytes(${maxLen});\n`;
            code += `        packet.${fieldStartingHere.name} = System.Text.Encoding.UTF8.GetString(raw_${fieldStartingHere.name}).TrimEnd();\n`;
            currentByte += maxLen;
          }
        }
      }
    }

    // Safety check
    if (currentByte <= prevByte) {
      currentByte++;
    }
  }

  code += `
        return packet;
    }
}
`;

  if (hasVector) {
    code += `
public struct Vector3
{
    public float x;
    public float y;
    public float z;
    public Vector3(float x, float y, float z) { this.x = x; this.y = y; this.z = z; }
}
`;
  }

  return code;
}
