import type { PacketField } from '../../types';
import { calculatePacketLayout, getFieldBitWidth } from '../bitPacking';

function getUnityStringInfo(maxLen: number): { className: string; byteWidth: number } {
  if (maxLen < 32) return { className: 'FixedString32Bytes', byteWidth: 32 };
  if (maxLen < 64) return { className: 'FixedString64Bytes', byteWidth: 64 };
  if (maxLen < 128) return { className: 'FixedString128Bytes', byteWidth: 128 };
  if (maxLen < 512) return { className: 'FixedString512Bytes', byteWidth: 512 };
  return { className: 'FixedString4096Bytes', byteWidth: 4096 };
}

export function generateUnityCode(fields: PacketField[]): string {
  const { layoutFields, totalBytes } = calculatePacketLayout(fields);
  
  let code = `// Unity Netcode for GameObjects (NGO) Serialization
// Automatically generated by BitPacker: Visual Game Netcode Designer

using Unity.Netcode;
using Unity.Collections;
using System;

public struct NetworkPacket : INetworkSerializable
{
`;

  // Fields declarations
  fields.forEach(f => {
    if (f.type === 'bool') {
      code += `    public bool ${f.name};\n`;
    } else if (f.type === 'int') {
      code += `    public int ${f.name};\n`;
    } else if (f.type === 'float') {
      code += `    public float ${f.name};\n`;
    } else if (f.type === 'vector3') {
      code += `    public UnityEngine.Vector3 ${f.name};\n`;
    } else if (f.type === 'string') {
      const stringInfo = getUnityStringInfo(f.maxStringLength || 16);
      code += `    public ${stringInfo.className} ${f.name}; // Optimized Fixed String size ${stringInfo.byteWidth}B\n`;
    }
  });

  code += `
    // Interface implementation
    public void NetworkSerialize<T>(BufferSerializer<T> serializer) where T : IReaderWriter
    {
        if (serializer.IsWriter)
        {
            var writer = serializer.GetFastBufferWriter();
            Write(ref writer);
        }
        else
        {
            var reader = serializer.GetFastBufferReader();
            Read(ref reader);
        }
    }

    private void Write(ref FastBufferWriter writer)
    {
        // Enforce boundary safety check
        if (!writer.TryBeginWrite(${totalBytes}))
        {
            throw new Exception("FastBufferWriter overflow, cannot serialize NetworkPacket.");
        }

`;

  // Pack bit-fields
  const byteRegisters: Record<number, { field: typeof layoutFields[0]; startBit: number; endBit: number }[]> = {};
  layoutFields.forEach(lf => {
    if (lf.bitWidthCalculated <= 8 && lf.byteIndexStart === lf.byteIndexEnd) {
      const byteIdx = lf.byteIndexStart;
      if (!byteRegisters[byteIdx]) byteRegisters[byteIdx] = [];
      byteRegisters[byteIdx].push({
        field: lf,
        startBit: lf.bitOffsetInByteStart,
        endBit: lf.bitOffsetInByteEnd
      });
    }
  });

  let currentByte = 0;
  while (currentByte < totalBytes) {
    const prevByte = currentByte;
    const bitFields = byteRegisters[currentByte];
    
    if (bitFields && bitFields.length > 0) {
      code += `        // Pack byte register ${currentByte}\n`;
      code += `        byte reg${currentByte} = 0;\n`;
      
      bitFields.forEach(bf => {
        const mask = (1 << bf.field.bitWidthCalculated) - 1;
        if (bf.field.type === 'bool') {
          code += `        if (${bf.field.name}) reg${currentByte} |= (byte)(1 << ${bf.startBit});\n`;
        } else if (bf.field.type === 'int') {
          let valExpr = bf.field.name;
          if (bf.field.minValue !== undefined) {
            valExpr = `(${bf.field.name} - ${bf.field.minValue})`;
          }
          code += `        int val_${bf.field.name} = Math.Clamp(${valExpr}, 0, ${mask});\n`;
          code += `        reg${currentByte} |= (byte)((val_${bf.field.name} & 0x${mask.toString(16)}) << ${bf.startBit});\n`;
        } else if (bf.field.type === 'float' && bf.field.floatType === 'quantized') {
          const min = bf.field.minValue ?? 0;
          const max = bf.field.maxValue ?? 1;
          const prec = bf.field.precision ?? 0.1;
          code += `        float clamped_${bf.field.name} = Math.Clamp(${bf.field.name}, ${min}f, ${max}f);\n`;
          code += `        int step_${bf.field.name} = (int)Math.Round((clamped_${bf.field.name} - ${min}f) / ${prec}f);\n`;
          code += `        reg${currentByte} |= (byte)((step_${bf.field.name} & 0x${mask.toString(16)}) << ${bf.startBit});\n`;
        }
      });
      
      code += `        writer.WriteValueSafe(reg${currentByte});\n`;
      currentByte++;
    } else {
      const fieldStartingHere = layoutFields.find(lf => lf.byteIndexStart === currentByte);
      if (fieldStartingHere) {
        code += `        // Field: ${fieldStartingHere.name} (${fieldStartingHere.type})\n`;
        
        if (fieldStartingHere.type === 'int' && fieldStartingHere.bitWidthCalculated > 8) {
          const width = fieldStartingHere.bitWidthCalculated;
          let valExpr = fieldStartingHere.name;
          if (fieldStartingHere.minValue !== undefined) {
            valExpr = `(${fieldStartingHere.name} - ${fieldStartingHere.minValue})`;
          }
          if (width <= 16) {
            code += `        writer.WriteValueSafe((ushort)${valExpr});\n`;
            currentByte += 2;
          } else {
            code += `        writer.WriteValueSafe((uint)${valExpr});\n`;
            currentByte += 4;
          }
        } else if (fieldStartingHere.type === 'float') {
          if (fieldStartingHere.floatType === 'single') {
            code += `        writer.WriteValueSafe(${fieldStartingHere.name});\n`;
            currentByte += 4;
          } else if (fieldStartingHere.floatType === 'half') {
            code += `        writer.WriteValueSafe((Half)${fieldStartingHere.name});\n`;
            currentByte += 2;
          }
        } else if (fieldStartingHere.type === 'vector3') {
          if (fieldStartingHere.vectorType === 'full') {
            code += `        writer.WriteValueSafe(${fieldStartingHere.name}.x);\n`;
            code += `        writer.WriteValueSafe(${fieldStartingHere.name}.y);\n`;
            code += `        writer.WriteValueSafe(${fieldStartingHere.name}.z);\n`;
            currentByte += 12;
          } else {
            const min = fieldStartingHere.minValue ?? -50;
            const max = fieldStartingHere.maxValue ?? 50;
            const prec = fieldStartingHere.vectorPrecision ?? 0.1;
            const compWidth = getFieldBitWidth(fieldStartingHere) / 3;
            const castType = compWidth <= 8 ? 'byte' : (compWidth <= 16 ? 'ushort' : 'uint');
            const inc = compWidth <= 8 ? 1 : (compWidth <= 16 ? 2 : 4);
            
            code += `        writer.WriteValueSafe((${castType})Math.Round((Math.Clamp(${fieldStartingHere.name}.x, ${min}f, ${max}f) - ${min}f) / ${prec}f));\n`;
            code += `        writer.WriteValueSafe((${castType})Math.Round((Math.Clamp(${fieldStartingHere.name}.y, ${min}f, ${max}f) - ${min}f) / ${prec}f));\n`;
            code += `        writer.WriteValueSafe((${castType})Math.Round((Math.Clamp(${fieldStartingHere.name}.z, ${min}f, ${max}f) - ${min}f) / ${prec}f));\n`;
            currentByte += inc * 3;
          }
        } else if (fieldStartingHere.type === 'string') {
          const stringInfo = getUnityStringInfo(fieldStartingHere.maxStringLength || 16);
          code += `        writer.WriteValueSafe(${fieldStartingHere.name});\n`;
          currentByte += stringInfo.byteWidth;
        }
      }
    }

    // Safety check
    if (currentByte <= prevByte) {
      currentByte++;
    }
  }

  code += `    }

    private void Read(ref FastBufferReader reader)
    {
        if (!reader.TryBeginRead(${totalBytes}))
        {
            throw new Exception("FastBufferReader underflow, cannot deserialize NetworkPacket.");
        }

`;

  currentByte = 0;
  while (currentByte < totalBytes) {
    const prevByte = currentByte;
    const bitFields = byteRegisters[currentByte];
    
    if (bitFields && bitFields.length > 0) {
      code += `        // Unpack byte register ${currentByte}\n`;
      code += `        reader.ReadValueSafe(out byte reg${currentByte});\n`;
      
      bitFields.forEach(bf => {
        const mask = (1 << bf.field.bitWidthCalculated) - 1;
        if (bf.field.type === 'bool') {
          code += `        ${bf.field.name} = (reg${currentByte} & (1 << ${bf.startBit})) != 0;\n`;
        } else if (bf.field.type === 'int') {
          let expr = `(reg${currentByte} >> ${bf.startBit}) & 0x${mask.toString(16)}`;
          if (bf.field.minValue !== undefined) {
            expr = `(${expr}) + ${bf.field.minValue}`;
          }
          code += `        ${bf.field.name} = ${expr};\n`;
        } else if (bf.field.type === 'float' && bf.field.floatType === 'quantized') {
          const min = bf.field.minValue ?? 0;
          const prec = bf.field.precision ?? 0.1;
          code += `        int step_${bf.field.name} = (reg${currentByte} >> ${bf.startBit}) & 0x${mask.toString(16)};\n`;
          code += `        ${bf.field.name} = (float)(step_${bf.field.name} * ${prec}f + ${min}f);\n`;
        }
      });
      currentByte++;
    } else {
      const fieldStartingHere = layoutFields.find(lf => lf.byteIndexStart === currentByte);
      if (fieldStartingHere) {
        code += `        // Unpack field: ${fieldStartingHere.name} (${fieldStartingHere.type})\n`;
        
        if (fieldStartingHere.type === 'int' && fieldStartingHere.bitWidthCalculated > 8) {
          const width = fieldStartingHere.bitWidthCalculated;
          const castType = width <= 16 ? 'ushort' : 'uint';
          code += `        reader.ReadValueSafe(out ${castType} raw_${fieldStartingHere.name});\n`;
          let expr = `raw_${fieldStartingHere.name}`;
          if (fieldStartingHere.minValue !== undefined) {
            expr = `(${expr}) + ${fieldStartingHere.minValue}`;
          }
          code += `        ${fieldStartingHere.name} = (int)${expr};\n`;
          currentByte += width / 8;
        } else if (fieldStartingHere.type === 'float') {
          if (fieldStartingHere.floatType === 'single') {
            code += `        reader.ReadValueSafe(out ${fieldStartingHere.name});\n`;
            currentByte += 4;
          } else if (fieldStartingHere.floatType === 'half') {
            code += `        reader.ReadValueSafe(out Half rawHalf_${fieldStartingHere.name});\n`;
            code += `        ${fieldStartingHere.name} = (float)rawHalf_${fieldStartingHere.name};\n`;
            currentByte += 2;
          }
        } else if (fieldStartingHere.type === 'vector3') {
          if (fieldStartingHere.vectorType === 'full') {
            code += `        reader.ReadValueSafe(out float vx_${fieldStartingHere.name});\n`;
            code += `        reader.ReadValueSafe(out float vy_${fieldStartingHere.name});\n`;
            code += `        reader.ReadValueSafe(out float vz_${fieldStartingHere.name});\n`;
            code += `        ${fieldStartingHere.name} = new UnityEngine.Vector3(vx_${fieldStartingHere.name}, vy_${fieldStartingHere.name}, vz_${fieldStartingHere.name});\n`;
            currentByte += 12;
          } else {
            const min = fieldStartingHere.minValue ?? -50;
            const prec = fieldStartingHere.vectorPrecision ?? 0.1;
            const compWidth = getFieldBitWidth(fieldStartingHere) / 3;
            const readType = compWidth <= 8 ? 'byte' : (compWidth <= 16 ? 'ushort' : 'uint');
            const inc = compWidth <= 8 ? 1 : (compWidth <= 16 ? 2 : 4);
            
            code += `        reader.ReadValueSafe(out ${readType} sx_${fieldStartingHere.name});\n`;
            code += `        reader.ReadValueSafe(out ${readType} sy_${fieldStartingHere.name});\n`;
            code += `        reader.ReadValueSafe(out ${readType} sz_${fieldStartingHere.name});\n`;
            code += `        ${fieldStartingHere.name}.x = sx_${fieldStartingHere.name} * ${prec}f + ${min}f;\n`;
            code += `        ${fieldStartingHere.name}.y = sy_${fieldStartingHere.name} * ${prec}f + ${min}f;\n`;
            code += `        ${fieldStartingHere.name}.z = sz_${fieldStartingHere.name} * ${prec}f + ${min}f;\n`;
            currentByte += inc * 3;
          }
        } else if (fieldStartingHere.type === 'string') {
          const stringInfo = getUnityStringInfo(fieldStartingHere.maxStringLength || 16);
          code += `        reader.ReadValueSafe(out ${fieldStartingHere.name});\n`;
          currentByte += stringInfo.byteWidth;
        }
      }
    }

    // Safety check
    if (currentByte <= prevByte) {
      currentByte++;
    }
  }

  code += `    }
}
`;

  return code;
}
